### ISSUE TITLE
[REQ] Agent Patch System

### ISSUE THREAD

**Issue by ianlucas** [ianlucas/cs2-inventory-simulator#37]
Patches can be applied in multiple slots of an agent, and it's not an equippable item like a pin. It's more like a sticker for agents.

**Comment by crashzk** [comment]
Here is a suggestion for creating a rule for Patch as well.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/b966c48c-b08f-47e5-96fa-0d892a8ec27e)

Create rules so that we can control whether the user can apply it to an agent or even remove it if it is already applied to the agent.
