### ISSUE TITLE
[BUG] Duplicate pin when the site is in a language other than English

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#45]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/7a58f0d6-7ff5-4cc6-a156-15aa94af8eeb)

In the case of the Pin category, from what I noticed, if you put it in English everything is fine, PT-BR is duplicated.

**_Note: From what I've seen it only happens in PT-BR, other languages ​​are fine._**

**Comment by ianlucas** [comment]
It's the same as issue #5, note the difference between the altname "Collectible" and "Commodity". Also they're in English because there's not translation for them in [csgo_brazilian.txt](https://[raw.githubusercontent.com/SteamDatabase/GameTracking-CS2/master/game/csgo/pak01_dir/resource/csgo_brazilian.txt](https://raw.githubusercontent.com/SteamDatabase/GameTracking-CS2/master/game/csgo/pak01_dir/resource/csgo_brazilian.txt)).
