### ISSUE TITLE
[REQ] Implement Edit Craft

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#8]
Would it be possible to have an option to edit the skin we crafted again? Edit nametag, stickers, stattrak, etc...

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/45b14824-e469-41d4-a39c-76bf4818158a)

**Comment by ianlucas** [comment]
At this moment I'm focusing on simulating as close as possible how a player would interact with their inventory items, so name tags and applying/scraping stickers will be the way for changing some attributes. Wear and StatTrak (except StatTrak swap) will remain non-editable for the crafted item.

Craft is just a convenient way to create items. In the future I'll add a "sandbox" option to allow editing existing items instead of doing it the in-game way.
