### ISSUE TITLE
[BUG] New stable version build error

### ISSUE THREAD

**Issue by SkyJust4Fun** [ianlucas/cs2-inventory-simulator#90]
[vite]: Rollup failed to resolve import "steamapi" from "/var/www/html/skins/app/api-strategy.server.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

I not an expert on this.. but how can i fix this xD?

**Comment by ianlucas** [comment]
Did you get this error when using `1.0.0` release?

**Comment by SkyJust4Fun** [comment]
Might be dumb but, Which files am i suppose to download? Only the relase 1.0.0 then follow self hosting or download main and follow self hosting x-x?

**Comment by ianlucas** [comment]
The safest option is the released version, but I really don't have a roadmap or schedule for when new versions are released (I'm planning on releasing `1.1.0` tomorrow tho).

If you want to have the latest updates, then cloning/downloading the main branch is the way, but keep in mind you may face issues like this one (that usually should be fixed by me).

**Comment by SkyJust4Fun** [comment]
Yhe the main branch is getting me this error the 1.0.0 isnt :) only getting an error on start from post gress but already changed to mysql :v

**Comment by ianlucas** [comment]
Should be fixed now, please reopen if it happens again.
